### ISSUE TITLE
Misspelled fossil names

### ISSUE THREAD

**Issue by Nope-avi** [rmlamarche/acnh-tracker-issues#1]
### Incorrect/Missing Data

Type: [Fossil]

What's wrong?: It seems the Megaloceros and Megacerops parts were mixed up; I just checked my museum, and the one with only one half found is not the Megacerops, it's the Megaloceros. It should say Megaloceros left half and right half, not Megalocerops left and right halves, and the Megacerops is the one that has a tail, torso, and skull so add the p to it instead of Megaceros . It's just a spelling error I think.

**Comment by rmlamarche** [comment]
Thanks! I'll look into this

**Comment by rmlamarche** [comment]
Fixed

Megalocerops -> megaloceros
Megaceros -> Megacerops
