### ISSUE TITLE
Does Not Load

### ISSUE THREAD

**Issue by MisterBooBear** [rmlamarche/acnh-tracker-issues#3]
whenever I try to log in by clicking the log in with google button, the page doesn't change but the load screen starts, and after almost a minute I'm left at a blank page that only has error up in the top left corner. It cannot be from my end, as my internet connection is strong and stable.

**Comment by rmlamarche** [comment]
Hello - this was due to increased amounts of traffic on the site. The site has been upgraded so this should no longer be an issue. Sorry for the inconvenience!
